FROM python:3.12-slim

WORKDIR /srv/app

COPY app/requirements.txt /srv/app/requirements.txt
RUN pip install --no-cache-dir -r /srv/app/requirements.txt

COPY app /srv/app/app

ENV PYTHONPATH=/srv/app

CMD ["uvicorn", "app.blockchain_mock:app", "--host", "0.0.0.0", "--port", "8001"]
